#!/bin/bash

# usage:
#   composer sh
#       opens bash with composer available
#   composer <composer-command> [options]

# catch and exit when functions exit with error
set -e

# import these open_cli
source ~/docker-scripts/common.sh

# we save these for use in build_command
first_arg=$1
original_args=$@

build_command() {
    wdir=$1
    os=$2

    # create the command array
    if [ "$first_arg" = "sh" ]; then
        command_arr=( "bash" "--rcfile" "/$wdir/.bashrc" "-i" )
    else
        # user wants to run a composer command
        command_arr=( "composer" $original_args)
    fi

    echo ${command_arr[@]}
}

open_cli composer latest buster $@
